name: Steps Modifier

on:
  push:
    branches:
      - main

env:
  COUNTER_FILE: counter.txt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz

    - name: Run steps_modifier.py
      run: |
        python steps_modifier.py

    - name: Update counter
      run: |
        echo ${{ env.COUNTER }} > ${{ github.workspace }}/${{ env.COUNTER_FILE }}
