name: Scheduled Task

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 */2 * * *'

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      run: |
        python -c "
        import requests

        def modify_steps(username, password, steps):
            url = 'http://bs.svv.ink/index.php'
            data = {
                'username': username,
                'password': password,
                'steps': steps
            }

            response = requests.post(url, data=data)

            if response.status_code == 200:
                print('步数修改成功！')
            else:
                print('步数修改失败！')

        username = '15033296069'
        password = '20030101h'
        steps = 10000
        modify_steps(username, password, steps)
        "
